name: Find Card City - From 0 to 33
on:
  workflow_dispatch:
  schedule:
    - cron: "11 7,12,18 * * *" # Kyiv time at 9:11, 16:11, 22:11
jobs:
  findAll:
    uses: ./.github/workflows/playwright.yml
    with:
      from: 0
      to: 33
      version: v1
    secrets:
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
