name: Find Card City - From 66 to 100
on:
  workflow_dispatch:
  schedule:
    - cron: "5 6,13 * * *" # 8:05 am Kyiv time
jobs:
  findAll:
    uses: ./.github/workflows/playwright.yml
    with:
      from: 66
      to: 100
      version: v1
    secrets:
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
