name: Find Card City - From 33 to 66
on:
  workflow_dispatch:
  schedule:
    - cron: "25 5,14 * * *" # 8:25 am Kyiv time
jobs:
  findAll:
    uses: ./.github/workflows/playwright.yml
    with:
      from: 33
      to: 66
      version: v1
    secrets:
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
