name: Find Card All
on:
  workflow_dispatch:
  schedule:
    - cron: "33 6,13,19 * * *"
jobs:
  findAll:
    uses: ./.github/workflows/playwright.yml
    with:
        from: 0
        to: 100
        version: v2
    secrets:
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
