name: Find Card City - From 33 to 66
on:
  workflow_dispatch:
  schedule:
    - cron: "25 8 * * *" # Kyiv time at 9:25, 14:25, 20:25
jobs:
  findAll:
    uses: ./.github/workflows/playwright.yml
    with:
      from: 33
      to: 66
      version: v1
    secrets:
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
